[features]
seeds = false
skip-lint = false
[programs.localnet]
transfer = "6qkux1rvxXxvx7sMTWBm8AqrQPrLNTaQgwYs292Wh5iT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/minhdo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
