[features]
seeds = false
skip-lint = false
[programs.localnet]
trade_nft = "4kVr2h7SZkWVV7DBoYEkL4gV7bzcp2T9TbuFqmNBcnUc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/minhdo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
