[features]
seeds = false
skip-lint = false
[programs.localnet]
trade_nft = "3nDusEFjqioKWzhP6uXxqMSwk2rNMjB2Th8drLAGthh1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/minhdo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
