[features]
seeds = false
skip-lint = false
[programs.localnet]
counter = "4UW83kGzjovz2gujn87fcDG7oEhjp43VgjHvaoAaCtPc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/minhdo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
