[features]
seeds = false
skip-lint = false
[programs.localnet]
coin_flip = "4LtpC4z4WpJcApWXM8Hm5N7iUP1C5j51NVyyYj334L3w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/minhdo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
