[features]
seeds = false
skip-lint = false
[programs.localnet]
transfer_pool = "51aT3n5amGTQMT4P5V1xaAQYti83ajaqkcqjJrRPJKg9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/minhdo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
